# Generated by Django 3.1.1 on 2020-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender_female',
            field=models.BooleanField(default='False'),
        ),
    ]
